language: node_js
node_js:
  - "8"
script:
  - yarn test
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN ./node_modules/.bin/codeclimate-test-reporter < coverage/lcov.info
  - yarn build
  - NOW_TOKEN=$NOW_TOKEN CI=TravisCI yarn deploy
